
def get_books():
    """
    Get books plus metadata.
    """
    return {
        code: {
            "collection": collection,
            "code": code,
            "name": name,
            "chapters": chapters,
            "aliases": [a for a in aliases.split(",")] if aliases else [],
        }
        for collection, code, name, chapters, aliases in _BOOKS
    }


_BOOKS = [
    ("Torah", "Gen", "Genesis", 50, "Ge,Gn"),
    ("Torah", "Exod", "Exodus", 40, "Ex,Exo"),
    ("Torah", "Lev", "Leviticus", 27, "Le,Lv"),
    ("Torah", "Num", "Numbers", 36, "Nu,Nm,Nb"),
    ("Torah", "Deut", "Deuteronomy", 34, "De,Dt"),
    ("Neviim", "Josh", "Joshua", 24, "Jos,Jsh"),
    ("Neviim", "Judg", "Judges", 21, "Jdg,Jg,Jdgs"),
    ("Neviim", "1Sam", "1 Samuel", 31, "1Sm,1Sa"),
    ("Neviim", "2Sam", "2 Samuel", 24, "2Sm,2Sa"),
    ("Neviim", "1Kgs", "1 Kings", 22, "1Ki,1Kin"),
    ("Neviim", "2Kgs", "2 Kings", 25, "2Ki,2Kin"),
    ("Neviim", "Isa", "Isaiah", 66, "Is"),
    ("Neviim", "Jer", "Jeremiah", 52, "Je,Jr"),
    ("Neviim", "Ezek", "Ezekiel", 48, "Eze,Ezk"),
    ("Neviim", "Hos", "Hosea", 14, "Ho"),
    ("Neviim", "Joel", "Joel", 3, "Jl"),
    ("Neviim", "Amos", "Amos", 9, "Am"),
    ("Neviim", "Obad", "Obadiah", 1, "Ob"),
    ("Neviim", "Jonah", "Jonah", 4, "Jnh,Jon"),
    ("Neviim", "Mic", "Micah", 7, "Mc"),
    ("Neviim", "Nah", "Nahum", 3, "Na"),
    ("Neviim", "Hab", "Habakkuk", 3, "Hb"),
    ("Neviim", "Zeph", "Zephaniah", 3, "Zep,Zp"),
    ("Neviim", "Hag", "Haggai", 2, "Hg"),
    ("Neviim", "Zech", "Zechariah", 14, "Zec,Zc"),
    ("Neviim", "Mal", "Malachi", 4, "Ml"),
    ("Ketuvim", "Ps", "Psalms", 150, "Psa,Pss,Psm,Pslm,Psalm"),
    ("Ketuvim", "Prov", "Proverbs", 31, "Pro,Prv,Pr"),
    ("Ketuvim", "Job", "Job", 42, "Jb"),
    ("Ketuvim", "Song", "Song of Songs", 8, "Sos,So,Songs,Song of Solomon"),
    ("Ketuvim", "Ruth", "Ruth", 4, "Rth,Ru"),
    ("Ketuvim", "Lam", "Lamentations", 5, "La"),
    ("Ketuvim", "Eccl", "Ecclesiastes", 12, "Ec,Ecc,Eccle"),
    ("Ketuvim", "Esth", "Esther", 10, "Est,Es"),
    ("Ketuvim", "Dan", "Daniel", 12, "Da,Dn"),
    ("Ketuvim", "Ezra", "Ezra", 10, "Ezr,Ez"),
    ("Ketuvim", "Neh", "Nehemiah", 13, "Ne"),
    ("Ketuvim", "1Chr", "1 Chronicles", 29, "1Ch,1Chron"),
    ("Ketuvim", "2Chr", "2 Chronicles", 36, "2Ch,2Chron"),
    ("New Testament", "Matt", "Matthew", 28, "Mt,Mat"),
    ("New Testament", "Mark", "Mark", 16, "Mrk,Mar,Mk,Mr"),
    ("New Testament", "Luke", "Luke", 24, "Luk,Lk"),
    ("New Testament", "John", "John", 21, "Joh,Jhn,Jn"),
    ("New Testament", "Acts", "Acts", 28, "Act,Ac"),
    ("New Testament", "Rom", "Romans", 16, "Ro,Rm"),
    ("New Testament", "1Cor", "1 Corinthians", 16, "1Co"),
    ("New Testament", "2Cor", "2 Corinthians", 13, "2Co"),
    ("New Testament", "Gal", "Galatians", 6, "Ga"),
    ("New Testament", "Eph", "Ephesians", 6, "Ephes"),
    ("New Testament", "Phil", "Philippians", 4, "Php,Pp"),
    ("New Testament", "Col", "Colossians", 4, "Co"),
    ("New Testament", "1Thess", "1 Thessalonians", 5, "1Thes,1Th"),
    ("New Testament", "2Thess", "2 Thessalonians", 3, "2Thes,2Th"),
    ("New Testament", "1Tim", "1 Timothy", 6, "1Ti"),
    ("New Testament", "2Tim", "2 Timothy", 4, "2Ti"),
    ("New Testament", "Titus", "Titus", 3, "Tit"),
    ("New Testament", "Phlm", "Philemon", 1, "Phm,Pm,Philem"),
    ("New Testament", "Heb", "Hebrews", 13, "He"),
    ("New Testament", "Jas", "James", 5, "Jm"),
    ("New Testament", "1Pet", "1 Peter", 5, "1Pe,1Pt"),
    ("New Testament", "2Pet", "2 Peter", 3, "2Pe,2Pt"),
    ("New Testament", "1John", "1 John", 5, "1Jhn,1Joh,1Jn"),
    ("New Testament", "2John", "2 John", 1, "2Jhn,2Joh,2Jn"),
    ("New Testament", "3John", "3 John", 1, "3Jhn,3Joh,3Jn"),
    ("New Testament", "Jude", "Jude", 1, "Jd,Jud"),
    ("New Testament", "Rev", "Revelation", 22, "Re"),
]
